name: Build maas-api Image

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: maas-api

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: maas-api/go.mod
          cache: true
          cache-dependency-path: maas-api/go.sum

      - name: Login to Quay.io
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}

      - name: Build and push latest image
        run: make build-image push-image REPO=quay.io/chkulkar/maas-api TAG=${{ github.event.pull_request.number }}